### ISSUE TITLE
NMS does not work properly, the IoU calculation is wrong.

### ISSUE THREAD

**Issue by takacsd** [hhj1897/face_detection#2]
When calculating the area of the rectangle, the code uses the `(x2-x1+1)*(y2-y1+1)` formula ([here](https://github.com/hhj1897/face_detection/blob/master/ibug/face_detection/retina_face/py_cpu_nms.py#L19) and [here](https://github.com/hhj1897/face_detection/blob/master/ibug/face_detection/retina_face/py_cpu_nms.py#L31-L33)).

This would be fine if the coordinates were integers and we would calculate in pixel space (it would mean that we consider the [x1, x2]x[y1,y2] closed 2d interval as the rectangle as opposed to the [x1, x2)x[y1,y2) half open intervals). I suppose this was the case in the original Fast R-CNN project.

But here we call this function with [0,1] normalized coordinates, which makes the IoU calculation wrong.
Practically it drops even the not overlapping detections. So the face detector only works properly when only one face is present on the image.

**Comment by hhj1897** [comment]
When py_cpu_nms is called, the coordinates are converted back to pixel space, not normalised to [0, 1]. Hence +1 doesn't make the results wrong.
